name: Generate documentation
env:
  POETRY_VERSION: "1.2.0b1"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

permissions:
  contents: write
  pull-requests: write

on: 
  push:
    paths:
      - 'examples/**'
      - 'inject_*.py'
      - '.github/workflows/docs.yml'
      - '**/README.md'
  workflow_dispatch:

jobs:
  rebuild-readme:
    name: Script building README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install poetry
        run: pipx install poetry==${POETRY_VERSION}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          architecture: x64
          cache: poetry
      - run: poetry install --with dev
      - run: poetry run python inject_readme.py
      - run: poetry run python examples/generate_documentation.py
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "docs: update markdown"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: docs
          delete-branch: true
          title: '[Docs] Update Markdown'
          body: |
            Update report
            - Updated with `examples/generate_documentation.py`
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            documentation
            automated pr
          assignees: danielloader
          reviewers: danielloader
          team-reviewers: |
            owners
            maintainers
          draft: false
