name: Generate documentation for gh-pages and release package to pypi
env:
  POETRY_VERSION: "1.2.0b1"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

permissions:
  contents: write
  pull-requests: write

on:
  release:
    types: [published]

jobs:
  build-docs:
    name: Build release to gh-pages release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry==${POETRY_VERSION}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          architecture: x64
          cache: poetry
      - run: poetry install --with docs
      - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - run: poetry version ${{ github.event.release.tag_name }}
      - run: poetry publish --build
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Bump version in-line with release
          file_pattern: pyproject.toml
      - uses: fregante/setup-git-user@v1
      - run: poetry run mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest
      - run: poetry run mike set-default --push latest
